<?php
show_buybutton = "Mostrar botón de compra"
show_stock = "Mostrar stock"
show_price = "Mostrar precio"
APP_Credits = "créditos"
APP_Shop = "Trofeos"
Shop_orders = "Pedidos"
Shop_my_orders = "Mis pedidos"
Shop_orders_list = "Listado de pedidos"
Shop_order = "Pedido"
Shop_products = "Trofeos"
Shop_products_list = "Listado de trofeos"
Shop_product = "Trofeo"
Shop_product_new = "Nuevo trofeo"
Shop_manufacturers = "Fabricantes"
Shop_manufacturers_list = "Listado de fabricantes"
Shop_manufacturer = "Fabricante"
Shop_manufacturer_new = "Nuevo fabricante"
Import_order_states = "Importar estados pedidos"
Comming_soon = "Próximo lanzamiento"
?>