---
options:
    allow_new: true
    forums_per_page: 5
    comments_per_page: 10
security:
    - 
        page: admin-validacion-foro-comentarios
        role: admin
    - 
        page: admin-validacion-foro-temas
        role: admin
